#: kivy 2.0.0

#: include AppData/kv_files/file_selector.kv
#: include AppData/kv_files/main_window.kv
#: include AppData/kv_files/loading_screen.kv
#: include AppData/kv_files/file_exporter.kv
#: include AppData/kv_files/pre_processing_screen.kv
#: include AppData/kv_files/directory_exporter.kv

WindowManager:
    FileSelector:
    MainWindow:
    LoadingScreen:
    FileExporter:
    PreProcessingScreen:
    DirectoryExporter:
